version: "3"
services:
  sql-service:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=devops
      - MYSQL_DATABASE=golf
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  webapp:
    image: gradle
    command: ["gradle", "bootRun"]
    volumes:
      - "./:/home/gradle/project"
    user: gradle
    working_dir: /home/gradle/project
    environment:
      - DBHOST=sql-service
    ports:
      - "8088:8088"
